//constants/index
const API_BASE_PATH = 'http://localhost:52940/api'

const actionConstants = {
    //API RETURNS
    LOGIN_SUCCESS: "LOG_IN_SUCCESS",
    LOGIN_FAILURE: "LOG_IN_FAILURE",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGITSER_FAILURE",

    //API CALLS
    REGISTER_USER: "REGISTER_USER",

    //UI
    LEFT_DRAWER_TOGGLE: "LEFT_DRAWER_TOGGLE",
    
    //REGISTRATION
    REGISTER_NAME_UPDATE: "REGISTER_NAME_UPDATE",
    REGISTER_EMAIL_UPDATE: "REGISTER_EMAIL_UPDATE",
    REGISTER_PASSWORD_UPDATE: "REGISTER_PASSWORD_UPDATE",
    REGISTER_STEPPER_CHANGE: "REGISTER_STEPPER_CHANGE",
    REGISTER_COMPLETE: "REGISTER_COMPLETE",
};

export { actionConstants, API_BASE_PATH };