//constants/index

const actionConstants = {
    LOGIN_SUCCESS: "LOG_IN_SUCCESS",
    LOGIN_FAILURE: "LOG_IN_FAILURE",
    REGISTER_STEPPER_FORWARD: "REGISTER_STEPPER_FORWARD",
    REGISTER_STEPPER_BACK: "REGISTER_STEPPER_BACK",
    LEFT_DRAWER_TOGGLE: "LEFT_DRAWER_TOGGLE",
};

export { actionConstants };